### ISSUE TITLE
Not working - Permission error

### ISSUE THREAD

**Issue by Scylla2020** [devanshbatham/DNSleuth#1]
Tried to run this on windows ubuntu and got an error. Tried running as admin too but no luck:

```
python3 dnsleuth.py
Traceback (most recent call last):
  File "/home/testaccount/DNSleuth/dnsleuth.py", line 54, in <module>
    sniff(filter="udp port 53", prn=dns_sniffer)
  File "/home/testaccount/.local/lib/python3.10/site-packages/scapy/sendrecv.py", line 1311, in sniff
    sniffer._run(*args, **kwargs)
  File "/home/testaccount/.local/lib/python3.10/site-packages/scapy/sendrecv.py", line 1171, in _run
    sniff_sockets[_RL2(iface)(type=ETH_P_ALL, iface=iface,
  File "/home/testaccount/.local/lib/python3.10/site-packages/scapy/arch/linux.py", line 484, in __init__
    self.ins = socket.socket(
  File "/usr/lib/python3.10/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by umutcamliyurt** [comment]
You need to use sudo command bro
